name: Nightly Hash Check
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: Nightly Hash Check
    runs-on: ubuntu-latest
    env:
      HASH_LOCATION: /tmp/hash
      URL: http://bin.entware.net/armv7sf-k3.2/installer
    steps:
      - name: Calculate Hash 
        uses: actions/checkout@v4
        run: |
          mkdir -p $HASH_LOCATION
          wget $URL/opkg.conf -O $HASH_LOCATION/opkg.conf
          wget $URL/ld-2.27.so -O $HASH_LOCATION/ld-2.27.so
          wget $URL/libc-2.27.so -O $HASH_LOCATION/libc-2.27.so
          wget $URL/libgcc_s.so.1 -O $HASH_LOCATION/libgcc_s.so.1
          wget $URL/libpthread-2.27.so -O $HASH_LOCATION/libpthread-2.27.so
          wget $URL/libpthread-2.27.so -O $HASH_LOCATION/libpthread-2.27.so
          cat $HASH_LOCATION/* | md5sum > $GITHUB_WORKSPACE/hash.txt
          git add .
          git commit -m "Updated Hash on $(date +'%Y-%m-%d')"
          git push

